version: "3.8"
services:
  neo4j:
    image: "neo4j:4.4.16"
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
      - ./scripts/lib/import:/var/lib/neo4j/import
    environment:
      - NEO4J_apoc_export_file_enabled=true 
      - NEO4J_apoc_import_file_enabled=true 
      - NEO4J_apoc_import_file_use__neo4j__config=true 
      - NEO4J_AUTH=neo4j/development
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
volumes:
  neo4j_data: