version: "3.8"
services:
  neo4j:
    image: "neo4j:latest"
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
      - ./scripts/lib/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/development
volumes:
  neo4j_data: